// glossary-data.js — Glosario Walmart Chile
const CATEGORIES = {
    all: { label: 'Todos', icon: '📚' },
    cultura: { label: 'Cultura & Valores', icon: '💛' },
    tienda: { label: 'Tienda & Sala', icon: '🏪' },
    inventario: { label: 'Inventario & Stock', icon: '📦' },
    ecommerce: { label: 'E-Commerce & Digital', icon: '🌐' },
    fulfillment: { label: 'Fulfillment & Logística', icon: '🚚' },
    merma: { label: 'Merma & Pérdidas', icon: '📉' },
    tech: { label: 'Tecnología', icon: '💻' },
    kpi: { label: 'KPIs & Métricas', icon: '📊' },
    rrhh: { label: 'RRHH & Onboarding', icon: '👥' },
    finanzas: { label: 'Finanzas & Compras', icon: '💰' },
    formatos: { label: 'Formatos & Áreas', icon: '🏢' },
};

const GLOSSARY = [
    // ===== CULTURA & VALORES =====
    { term: 'EDLP', full: 'Every Day Low Prices', desc: 'Filosofía central de Walmart: ofrecer precios bajos todos los días, no solo en promociones. Sam Walton decía: "Piensa en cuán poco puedo cobrar, no en cuánto".', cat: 'cultura' },
    { term: 'EDLC', full: 'Every Day Low Costs', desc: 'Mantener costos operativos bajos todos los días. Es lo que hace posible el EDLP. Cuidamos cada peso, optimizamos procesos y colaboramos con proveedores para ser eficientes.', cat: 'cultura' },
    { term: 'Spark', full: 'Símbolo Walmart ✦', desc: 'El símbolo junto al logo de Walmart. Representa el propósito: "Ahorramos dinero a las personas para que vivan mejor". Nos recuerda la importancia del cliente.', cat: 'cultura' },
    { term: '3 Creencias Básicas', full: 'Fundamentos de Sam Walton (1962)', desc: '1) Respeto por el individuo: valorar la singularidad de cada persona. 2) Servicio al cliente: "Solo hay un jefe... el cliente". 3) Búsqueda de la excelencia: superar el miedo al fracaso.', cat: 'cultura' },
    { term: 'Regla Sundown', full: 'Sundown Rule', desc: 'Si un cliente o asociado te pide algo, debes responderle ESE MISMO DÍA, aunque aún no tengas la respuesta final.', cat: 'cultura' },
    { term: 'Puerta Abierta', full: 'Open Door Policy', desc: 'Política para discutir preocupaciones de forma confidencial y sin represalias. Puedes hablar con cualquier nivel jerárquico para resolver inquietudes.', cat: 'cultura' },
    { term: 'Regla de los 3 Metros', full: '10-Foot Rule', desc: 'Cada vez que un asociado esté a menos de 3 metros de un cliente, debe detenerse, sonreír, mirarlo a los ojos y saludarlo.', cat: 'cultura' },
    { term: 'Hospitalidad Agresiva', full: 'Aggressive Hospitality', desc: 'Ir más allá para superar las expectativas del cliente. Ejemplo: un cajero parándose frente a la caja para invitar a los clientes a pagar.', cat: 'cultura' },
    { term: 'Actuar con Integridad', full: 'Act with Integrity', desc: 'Pilar cultural: Decir la verdad, ser justo y ser objetivo en todo lo que hacemos.', cat: 'cultura' },
    { term: 'Asociado', full: 'Associate', desc: 'Así se llama a cada colaborador en Walmart. No somos "empleados", somos asociados — socios en el negocio.', cat: 'cultura' },

    // ===== TIENDA & SALA =====
    { term: 'Góndola', full: 'Estantería de sala', desc: 'Estanterías ubicadas en los pasillos de los locales donde se exhiben los productos. Tienen su inicio/término en las cabeceras de góndola.', cat: 'tienda' },
    { term: 'Cabecera de Góndola', full: 'Endcap', desc: 'Inicio o término de las góndolas, frente a pasillos principales. Son áreas de mucha venta usadas para exhibiciones especiales y promociones.', cat: 'tienda' },
    { term: 'Planograma', full: 'Planogram', desc: 'Planificación de productos en la góndola basada en rentabilidad y preferencia del cliente. Es auditable y controlado. Define qué va dónde.', cat: 'tienda' },
    { term: 'Fleje', full: 'Shelf Label / Price Tag', desc: 'Etiqueta ubicada en la góndola con el precio, descripción, PLU y otra info del producto.', cat: 'tienda' },
    { term: 'Flejera', full: 'Label Holder', desc: 'Dispositivo plástico en las bandejas de las góndolas que sostiene los flejes de precio.', cat: 'tienda' },
    { term: 'Duchetas', full: 'Price Support (solo Líder)', desc: 'Soportes metálicos en góndolas para reforzar visualmente el precio. Se usan solo en formato Líder.', cat: 'tienda' },
    { term: 'Antena', full: 'Exhibidor de precios', desc: 'Pizarra plástica con detalle de promoción, producto y precio. Se usa para destacar ofertas en sala.', cat: 'tienda' },
    { term: 'Layout', full: 'Disposición de sala', desc: 'La distribución general de los productos en la sala de venta. Define cómo está organizado todo el local.', cat: 'tienda' },
    { term: 'Espacio Flex', full: 'Flex Space', desc: 'Espacio en sala destinado para productos suprimidos y/o que no están en el planograma.', cat: 'tienda' },
    { term: 'Exhibición', full: 'Display', desc: 'Actividad de promoción de un producto destacado a un precio atractivo en la sala de ventas.', cat: 'tienda' },
    { term: 'Beta', full: 'Acceso clientes', desc: 'Acceso por donde entran los clientes a la sala de venta.', cat: 'tienda' },
    { term: 'Gamma', full: 'Acceso colaboradores', desc: 'Entrada por donde ingresan los colaboradores/asociados del local.', cat: 'tienda' },
    { term: 'Regla del 4x1', full: 'Revisión de góndola', desc: 'Revisar 4 puntos críticos en cada metro de góndola: flejes correctos, limpieza general, presentación del producto y causa de quiebres.', cat: 'tienda' },
    { term: 'Apantallar', full: 'Facing / Fronting', desc: 'Colocar producto al nivel inicial de la góndola ante bajo stock, respetando planograma y marcando quiebres.', cat: 'tienda' },
    { term: 'POS', full: 'Point of Sale', desc: 'Dispositivo electrónico en el punto de venta que se conecta con el autorizador para registrar ventas y solicitar autorizaciones.', cat: 'tienda' },
    { term: 'Número de Armado', full: 'Planogram Build Number', desc: 'Código relativo al planograma que indica el orden estipulado para ubicar cada producto en sala.', cat: 'tienda' },

    // ===== INVENTARIO & STOCK =====
    { term: 'PLU', full: 'Price Look Up', desc: 'Código numérico interno asignado por el área Comercial a cada producto o servicio. Es como el "DNI" del producto en Walmart Chile.', cat: 'inventario' },
    { term: 'UPC', full: 'Universal Product Code', desc: 'Código de barra del producto. En Catálogo Extendido se usa "UPC GM".', cat: 'inventario' },
    { term: 'SKU', full: 'Stock Keeping Unit', desc: 'Unidad de mantenimiento de stock. Identificador único de un producto. En Walmart Chile se usa más "PLU" o "Item" internamente.', cat: 'inventario' },
    { term: 'Bin', full: 'Ubicación en bodega', desc: 'Ubicación codificada en bodega donde se almacena la mercadería antes de salir a sala de ventas.', cat: 'inventario' },
    { term: 'Bodega PAR', full: 'Bodega de Alto Riesgo', desc: 'Bodega destinada al resguardo de productos de alto riesgo/valor, cerrada con 2 candados.', cat: 'inventario' },
    { term: 'Rack', full: 'Estantería de bodega', desc: 'Estantería metálica donde se guardan los productos en la bodega/trastienda.', cat: 'inventario' },
    { term: 'Zona de Tránsito', full: 'Transit Zone', desc: 'Zona de trastienda donde se almacena la mercadería recién llegada del camión y que aún no se ha ingresado a BIN.', cat: 'inventario' },
    { term: 'Andén de Recepción', full: 'Receiving Dock', desc: 'Lugar destinado a la descarga de camiones. Es el inicio del ciclo de la mercadería en tienda.', cat: 'inventario' },
    { term: 'FIFO', full: 'First In, First Out', desc: 'Los productos se ordenan según su llegada para dar salida primero a los más antiguos.', cat: 'inventario' },
    { term: 'FEFO', full: 'First Expired, First Out', desc: 'Para perecederos: se da salida primero a los que tienen fecha de vencimiento más cercana.', cat: 'inventario' },
    { term: 'RRP / PDQ', full: 'Retail Ready Packing', desc: 'Empaque listo para exhibir directamente en góndola. Facilita la reposición rápida.', cat: 'inventario' },
    { term: 'SmartCount', full: 'Conteo Inteligente', desc: 'Herramienta de conteo de inventario a nivel de tienda para mantener la exactitud del stock.', cat: 'inventario' },

    // ===== E-COMMERCE & DIGITAL =====
    { term: 'Lider.cl', full: 'Plataforma E-Commerce', desc: 'Página web con servicios de e-commerce de Líder y Express de Líder. El canal digital principal de Walmart Chile.', cat: 'ecommerce' },
    { term: 'LiderApp', full: 'Aplicación móvil', desc: 'App móvil de Lider.cl para compras de supermercado desde el celular.', cat: 'ecommerce' },
    { term: 'Catálogo Extendido (CE/Catex)', full: 'Extended Catalog', desc: 'Productos inventariados que se venden directamente desde bodegas. No están disponibles en tiendas físicas, solo online.', cat: 'ecommerce' },
    { term: 'SOD', full: 'Supermercado On Demand', desc: 'Productos vendidos por Lider.cl usando el inventario real de tiendas físicas.', cat: 'ecommerce' },
    { term: 'DarkStore', full: 'Tienda oscura', desc: 'Tienda cerrada al público usada exclusivamente para operaciones de e-commerce (picking y despacho).', cat: 'ecommerce' },
    { term: 'Grey Store', full: 'Tienda gris', desc: 'Modelo operacional con surtido reducido, bodega como mini tienda para "Compra Simple".', cat: 'ecommerce' },
    { term: 'Marketplace', full: 'Marketplace Lider', desc: 'Plataforma donde vendedores externos (sellers) ofrecen sus productos a través de Lider.cl.', cat: 'ecommerce' },
    { term: 'ATS', full: 'Available to Sell', desc: '% del surtido disponible en IMS que está habilitado para comprar en Lider.cl.', cat: 'ecommerce' },
    { term: 'Omnicanalidad', full: 'Omnichannel', desc: 'Integración de la experiencia física y digital para ofrecer al cliente una experiencia consistente y sin fricciones, cómo, cuándo y dónde lo necesite.', cat: 'ecommerce' },
    { term: 'BAM', full: 'Brick And Mortar', desc: 'Experiencia de compra en supermercado en formato físico/presencial (lo opuesto a digital).', cat: 'ecommerce' },

    // ===== FULFILLMENT & LOGÍSTICA =====
    { term: 'Fulfillment', full: 'Proceso completo de entrega', desc: 'Proceso de administrar abastecimiento, inventario, preparar y entregar el producto: recepción del pedido → picking → packing → despacho → entrega.', cat: 'fulfillment' },
    { term: 'Picking', full: 'Armado de pedidos', desc: 'Proceso de armar/preparar pedidos recorriendo la sala y seleccionando los productos solicitados por el cliente.', cat: 'fulfillment' },
    { term: 'Picker', full: 'Armador de pedidos', desc: 'Colaborador interno o externo cuyo rol es armar pedidos en sala. Puede ser propio o crowdsourcing.', cat: 'fulfillment' },
    { term: 'Amida', full: 'App de picking', desc: 'Aplicación utilizada en el proceso de armado de pedidos en sala para Supermercado Pickup y Home Delivery.', cat: 'fulfillment' },
    { term: 'Home Delivery (HD)', full: 'Despacho a domicilio', desc: 'Modalidad donde el pedido online se entrega directamente en la dirección del cliente.', cat: 'fulfillment' },
    { term: 'Pickup', full: 'Retiro en tienda', desc: 'El cliente retira su pedido online en el local. SG 800/300 para Supermercado, SG 500 para Catálogo Extendido.', cat: 'fulfillment' },
    { term: 'LAT', full: 'Líder al Toque', desc: 'Modalidad de entrega para compras online con despacho el mismo día. ¡Rápido como un rayo!', cat: 'fulfillment' },
    { term: 'Staging', full: 'Zona de almacenamiento temporal', desc: 'Espacio físico donde se almacenan pedidos ya pickeados mientras esperan ser entregados al cliente.', cat: 'fulfillment' },
    { term: 'Sustituto', full: 'Producto alternativo', desc: 'Producto alternativo al solicitado por el cliente que mantiene características esenciales (mismo tipo, similar precio).', cat: 'fulfillment' },
    { term: 'Drop-shipping', full: 'Envío directo del proveedor', desc: 'Modelo donde los proveedores despachan directamente desde sus almacenes al cliente, sin pasar por tienda.', cat: 'fulfillment' },
    { term: '3PL', full: 'Third Party Logistics', desc: 'Empresa externa que se encarga de la logística (almacenamiento, transporte, distribución) por cuenta de Walmart.', cat: 'fulfillment' },
    { term: 'Crowdsourcing (Picking)', full: 'Picking externo', desc: 'Picking realizado a través de la app Amida por personal externo como Time Jobs, GyG, Boosmap, etc.', cat: 'fulfillment' },

    // ===== MERMA & PÉRDIDAS =====
    { term: 'Merma', full: 'Shrinkage', desc: 'Mercadería que pierde su capacidad de venta. Puede ser por vencimiento, daño, hurto u operación.', cat: 'merma' },
    { term: 'Merma Cliente', full: 'Customer Shrinkage', desc: 'Pérdida por inadecuada manipulación en sala, hurtos o consumos del cliente.', cat: 'merma' },
    { term: 'Merma Operacional', full: 'Operational Shrinkage', desc: 'Pérdida por inadecuada manipulación en trastienda por colaboradores, proveedores, distribución o mantención.', cat: 'merma' },
    { term: 'Merma Vencimiento', full: 'Expiry Shrinkage', desc: 'Pérdida por expiración o próxima fecha de vencimiento. Muy común en perecederos.', cat: 'merma' },
    { term: 'Total Loss', full: 'Pérdida total de inventario', desc: 'Cálculo de la pérdida total de inventario desde el último conteo hasta la fecha actual.', cat: 'merma' },

    // ===== TECNOLOGÍA =====
    { term: 'GTP', full: 'Global Tech Platform', desc: 'Plataforma tecnológica global de Walmart. En Chile, Strati evolucionó a DX (Developer Experience) dentro de GTP.', cat: 'tech' },
    { term: 'IMS', full: 'Inventory Management System', desc: 'Sistema de gestión de inventario. Trackea stock en tiendas y bodegas. En Chile: "IMS Wakanda".', cat: 'tech' },
    { term: 'WMS', full: 'Warehouse Management System', desc: 'Sistema para gestionar operaciones de bodega/almacén. Internamente también conocido como "Dr Strange".', cat: 'tech' },
    { term: 'OMS', full: 'Order Management System', desc: 'Gestiona el ciclo de vida de los pedidos. Chile tiene C-OMS (legacy) y PG-OMS (nuevo, basado en Pangaea).', cat: 'tech' },
    { term: 'SAP', full: 'Systems, Applications & Products', desc: 'Sistema ERP (Enterprise Resource Planning) usado para procesos financieros, RRHH y cadena de suministro.', cat: 'tech' },
    { term: 'WCNP', full: 'Walmart Cloud Native Platform', desc: 'Plataforma cloud nativa basada en Kubernetes para desplegar aplicaciones.', cat: 'tech' },
    { term: 'SSP', full: 'Solution Security Plan', desc: 'Revisión de cumplimiento de políticas y estándares de seguridad para cada solución/aplicación. Cada solución tiene un único SSP durante todo su ciclo de vida.', cat: 'tech' },
    { term: 'APM', full: 'Application Portfolio Management', desc: 'Gestión del portafolio de aplicaciones. También puede significar Agile Project Manager o Application Performance Management según contexto.', cat: 'tech' },
    { term: 'Element LLM Gateway', full: 'Gateway de IA', desc: 'Gateway interno de Walmart para modelos de lenguaje (LLM/IA). Mantiene todos los datos dentro de la red Eagle. Soporte: #element-genai-support en Slack.', cat: 'tech' },
    { term: 'Eagle', full: 'Red corporativa Walmart', desc: 'Red interna/corporativa de Walmart. Todos los datos sensibles deben mantenerse dentro de Eagle.', cat: 'tech' },
    { term: 'DX', full: 'Developer Experience', desc: 'Evolución de Strati. Producto dentro de GTP enfocado en la experiencia del desarrollador en Walmart Chile.', cat: 'tech' },
    { term: 'BYOD', full: 'Bring Your Own Device', desc: 'Política que permite a los asociados usar sus dispositivos personales para fines laborales.', cat: 'tech' },
    { term: '4 in the Box (4ITB)', full: 'Metodología colaborativa', desc: 'Metodología de trabajo donde Engineering + Product + UX + Business colaboran juntos en cada iniciativa.', cat: 'tech' },
    { term: 'GNFR', full: 'Goods Not For Resale', desc: 'Artículos comprados por Walmart que NO son para venta al cliente (ej: suministros de oficina, equipos, fixtures, limpieza).', cat: 'tech' },

    // ===== KPIs & MÉTRICAS =====
    { term: 'Quiebre', full: 'Out of Stock / Stockout', desc: 'Falta de producto en góndola. Al cliente se le dice "Producto no disponible". El enemigo número 1 de las ventas.', cat: 'kpi' },
    { term: 'NSG', full: 'Nivel de Servicio en Góndola', desc: 'Cantidad de productos que encuentra el cliente según planogramas. El objetivo es 100%.', cat: 'kpi' },
    { term: 'DOH', full: 'Days on Hand', desc: 'Días de inventario disponible. Fórmula: DOH = Inventario a Retail / Venta diaria promedio.', cat: 'kpi' },
    { term: 'Instock', full: 'Porcentaje en stock', desc: '% de ítems por tienda reabastecibles con inventario suficiente para al menos 1 día de venta.', cat: 'kpi' },
    { term: 'Completitud s/s', full: 'Completitud sin sustitución', desc: '% Unidades pickeadas sin sustitución / unidades solicitadas por el cliente. Mide qué tan bien cumplimos el pedido original.', cat: 'kpi' },
    { term: 'Completitud c/s', full: 'Completitud con sustitución', desc: '% Unidades pickeadas (contabilizando sustituciones) / unidades solicitadas. Mide cumplimiento total incluyendo alternativas.', cat: 'kpi' },
    { term: 'NTC', full: 'Nivel de Tiempo en Caja', desc: 'Métrica del nivel de servicio en cajas. Mide cuánto espera un cliente para pagar.', cat: 'kpi' },
    { term: 'CVI', full: 'Customer Value Index', desc: 'Score del producto dado su nivel de importancia para el cliente. Se usa en CATMAN para decidir surtido.', cat: 'kpi' },
    { term: 'WIC / WIC+', full: 'Walmart Intelligence Center', desc: 'Dashboard de KPIs de Walmart Chile. WIC+ es la versión mejorada con más indicadores y visualizaciones.', cat: 'kpi' },
    { term: 'Venta Comp', full: 'Comparable Sales', desc: 'Ventas comparables: compara ventas del período actual vs el mismo período del año anterior en las mismas tiendas.', cat: 'kpi' },
    { term: 'Ticket Promedio', full: 'Average Ticket', desc: 'Monto promedio de cada transacción/compra. Se calcula: Ventas totales / Número de transacciones.', cat: 'kpi' },

    // ===== RRHH & ONBOARDING =====
    { term: 'Workday', full: 'Plataforma de RRHH', desc: 'Plataforma cloud de RRHH para gestionar nómina, beneficios, tiempo, talento y datos organizacionales.', cat: 'rrhh' },
    { term: 'MyWalmart', full: 'Portal interno (ex OneWalmart/WIRE)', desc: 'Sistema de información interna con políticas, procesos, guías, ofertas laborales y noticias de la compañía. Antes se llamaba "The WIRE".', cat: 'rrhh' },
    { term: 'CCP', full: 'Clientes, Colaboradores y Partners', desc: 'Los tres pilares de stakeholders de Walmart Chile: Clientes, Colaboradores (asociados) y Partners (proveedores/socios).', cat: 'rrhh' },
    { term: 'Code Yellow', full: 'Iniciativa de estandarización', desc: 'Iniciativa de estandarización tecnológica que involucra a todos los equipos.', cat: 'rrhh' },
    { term: 'POP', full: 'Point of Purchase', desc: 'Material de exhibición en el punto de venta para incentivar compras. También: "Estrategia de Punto de Venta".', cat: 'rrhh' },

    // ===== FINANZAS & COMPRAS =====
    { term: 'CATMAN', full: 'Category Management', desc: 'Proceso donde los compradores eligen finelines y marcas para surtir las tiendas. Se hace 1 vez al año con 3 oportunidades de ajuste.', cat: 'finanzas' },
    { term: 'Margen', full: 'Margin', desc: 'Diferencia entre el precio de venta y el costo del producto. Es la ganancia bruta por cada ítem vendido.', cat: 'finanzas' },
    { term: 'Fineline', full: 'Sub-categoría de producto', desc: 'Nivel granular de clasificación de productos dentro de una categoría. Ej: dentro de "Bebidas" hay finelines como "Aguas", "Jugos", etc.', cat: 'finanzas' },
    { term: 'Markdown', full: 'Rebaja de precio', desc: 'Reducción de precio de un producto, generalmente para liquidar stock o por temporada.', cat: 'finanzas' },
    { term: 'Rollback', full: 'Reducción temporal de precio', desc: 'Reducción temporal del precio regular de un producto para impulsar ventas. Distintivo de Walmart.', cat: 'finanzas' },
    { term: 'Sell-through', full: 'Tasa de venta', desc: '% de unidades vendidas vs unidades recibidas en un período. Mide qué tan rápido se vende el inventario.', cat: 'finanzas' },

    // ===== FORMATOS & ÁREAS =====
    { term: 'Líder', full: 'Hipermercado', desc: 'Formato principal de hipermercado de Walmart Chile. Tiendas grandes con surtido completo de alimentos y mercancía general.', cat: 'formatos' },
    { term: 'Express de Líder', full: 'Formato convenience', desc: 'Formato de tienda más pequeño/conveniencia. Enfocado en compras rápidas y cercanas al hogar.', cat: 'formatos' },
    { term: 'ACP', full: 'Alimentación, Consumibles y Mascotas', desc: 'Área de la tienda que incluye alimentos, productos de consumo diario y productos para mascotas (Pets).', cat: 'formatos' },
    { term: 'GM', full: 'General Merchandise', desc: 'Área de la tienda con productos no comestibles: hogar, entretenimiento, hardlines, vestuario.', cat: 'formatos' },
    { term: 'PPS', full: 'Perecederos, Producción y Servicios', desc: 'Área de productos perecibles: carnes, pescados, frutas, panadería, etc. Todo lo fresco.', cat: 'formatos' },
    { term: 'GEC', full: 'Global eCommerce', desc: 'Organización Global de eCommerce de Walmart. Coordina la estrategia digital a nivel mundial.', cat: 'formatos' },
    { term: 'CAM', full: 'Central America', desc: 'Tenant de Centroamérica: Costa Rica, El Salvador, Honduras, Panamá, Guatemala, Nicaragua.', cat: 'formatos' },
];
